application: imi-imi
version: 1
runtime: python
api_version: 1


handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /favicon.ico
  static_files: static-files/images/favicon.ico
  upload: static-files/images/favicon.ico

- url: /robots.txt
  static_files: static-files/robots.txt
  upload: static-files/robots.txt

- url: /static-files
  static_dir: static-files

- url: /.*
  script: main.py


skip_files:
# Default stuff:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*

# imi-imi specific stuff:
- ^(.*/)?.*\.swp$
- ^(.*/)?IGNORE\.txt
